name: Docker CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Nginx Docker image
        run: |
          docker build -t my-nginx-image .
          docker tag my-nginx-image:latest ${{ secrets.DOCKER_USERNAME }}/nginx:${{ github.sha }}

      - name: Push Docker image to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
          docker push ${{ secrets.DOCKER_USERNAME }}/nginx:${{ github.sha }}

      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script: |
            # Stop and remove the existing container if it exists
            docker stop my-nginx-container || true
            docker rm my-nginx-container || true

            # Pull and run the Nginx container with the new image
            docker run -d --name my-nginx-container -p 80:80 ${{ secrets.DOCKER_USERNAME }}/nginx:${{ github.sha }}
